input CustomizableOptionInput {
    id: Int!
    value_string: String!
}

mutation addConfigurableToCart ($cart_id: String!, $quantity: Float!, $sku: String!, $options: [CustomizableOptionInput]) {
    addConfigurableProductsToCart(
        input: {
            cart_id: $cart_id, 
            cart_items: {
                data: { 
                    quantity: $quantity, 
                    sku: $sku 
                },
                customizable_options: $options
            }
        })
    {
        cart {
            items {
                id
                product {
                    id
                    name
                    sku
                    thumbnail {
                        label
                        url
                    }
                }
                quantity
            }
            prices {
                applied_taxes {
                    label
                    amount {
                        value
                    }
                }
                grand_total {
                    value
                }
                subtotal_excluding_tax {
                    value
                }
                subtotal_including_tax {
                    value
                }
                subtotal_with_discount_excluding_tax {
                    value
                }
            }
            total_quantity
            applied_coupons {
                code
            }
            shipping_addresses {
                selected_shipping_method {
                    carrier_code
                    carrier_title
                    method_code
                    method_title
                    amount {
                        value
                    }
                    base_amount {
                        value
                    }
                }
            }
        }
    }
}