mutation setPaymentMethods($cart_id: String!, $code: String!, $payer_id: String!, $token: String!) {
    setPaymentMethodOnCart (
        input: {
            cart_id: $cart_id,
            payment_method: {
                code: $code,
                paypal_express: {
                    payer_id: $payer_id,
                    token: $token
                }
            }
        }
    ){
        cart {
             items {
                id
                product {
                    id
                    name
                    sku
                }
                quantity
            }
            prices {
                applied_taxes {
                    label
                    amount {
                        value
                    }
                }
                grand_total {
                    value
                }
                subtotal_excluding_tax {
                    value
                }
                subtotal_including_tax {
                    value
                }
                subtotal_with_discount_excluding_tax {
                    value
                }
            }
            applied_coupon {
                code
            }
            shipping_addresses {
                available_shipping_methods {
                    amount {
                        value
                    }
                    available
                    base_amount  {
                        value
                    }
                    carrier_code
                    carrier_title
                    method_code
                    method_title
                    price_excl_tax  {
                        value
                    }
                    price_incl_tax  {
                        value
                    }
                }
                selected_shipping_method {
                    carrier_code
                    carrier_title
                    method_code
                    method_title
                    amount {
                        value
                    }
                    base_amount {
                        value
                    }
                }
            }
            selected_payment_method {
                code
                title
            }
        }
    }
}
