const ROUTER_SET: Set<String> = new Set(['category', 'product', 'page'])
const DEFAULT_LOCALE: string = 'en_US'
const FILTER_COLOR_WHITE_BORDER: string = '#000'
const DEFAULT_CATEGORY_PAGE_SIZE: number = 8
const DEFAULT_CATEGORY_SORT_KEY: string = 'position'
const DEFAULT_CATEGORY_SORT_VALUE: string = 'ASC'
const DEFAULT_PRODUCT_CONIGURABLE: string = 'configurable'

export {
    ROUTER_SET,
    DEFAULT_LOCALE,
    FILTER_COLOR_WHITE_BORDER,
    DEFAULT_CATEGORY_PAGE_SIZE,
    DEFAULT_CATEGORY_SORT_KEY,
    DEFAULT_CATEGORY_SORT_VALUE,
    DEFAULT_PRODUCT_CONIGURABLE
}